# Generated by Django 4.2.4 on 2023-11-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gan', '0002_texttoimagephoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='esrganPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gan_photos/esrgan/')),
            ],
        ),
        migrations.DeleteModel(
            name='ganPhoto',
        ),
    ]
