# Generated by Django 4.2.4 on 2023-12-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gan', '0006_imagetoimagephoto_guidance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpaintphoto',
            name='guidance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inpaintphoto',
            name='model_used',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='inpaintphoto',
            name='strength',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
