# Generated by Django 4.2.4 on 2023-09-06 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_session_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='password',
            field=models.CharField(default='password', max_length=100),
        ),
    ]
