# Generated by Django 4.2.4 on 2023-09-12 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_photo_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='selected_to_edit',
            field=models.BooleanField(default=False),
        ),
    ]
