# Generated by Django 4.2.4 on 2023-09-23 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_photo_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='thumbnail_medium',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails_medium/'),
        ),
    ]
